[build.environment]
  DART_SASS_VERSION = "1.97.3"
  GO_VERSION = "1.26.0"
  HUGO_VERSION = "0.156.0"
  NODE_VERSION = "24.13.1"
  NPM_VERSION = "11.8.0"
  TZ = "Europe/Paris"

[build]
  publish = "public"
  command = """\
  git config core.quotepath false && \
  npm install && \
  echo "URL=[$URL]" && \
  # strip CR/newline in $URL before passing to Hugo
  hugo build --gc --minify --baseURL "$(printf '%s' "$URL" | tr -d '\r\n')" \
  echo "end of build command"
  """

#[context.production]
  #command = "npm ci --include=dev && npm run build"

#[context.deploy-preview]
  #command = "npm ci --include=dev && npm run build"

#[context.branch-deploy]
  #command = "npm ci --include=dev && npm run build"

#[context.next]
  #command = "npm ci --include=dev && npm run build"

[dev]
  framework = "#custom"
  command = "bun run dev"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

# Redirects and rewrites — https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file

# Custom headers — https://docs.netlify.com/routing/headers/#syntax-for-the-netlify-configuration-file
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; manifest-src 'self'; connect-src 'self'; font-src 'self'; img-src 'self' https://avatars.githubusercontent.com data:; script-src 'self' https://code.jquery.com https://func-api-qqr6sxmfuyb34.azurewebsites.net 'nonce-dXNlcj0iaGVsbG8iLGRvbWFpbj0iaGVua3ZlcmxpbmRlLmNvbSIsZG9jdW1lbnQud3JpdGUodXNlcisiQCIrZG9tYWluKTs=' 'sha256-aWZ3y/RxbBYKHXH0z8+8ljrHG1mSBvyzSfxSMjBSaXk='; style-src 'self'"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin"
    Permissions-Policy = "geolocation=(self), microphone=(), camera=()"
    Cache-Control = "max-age=0, must-revalidate, public"
    Access-Control-Allow-Origin = "*"

# Redirects and rewrites — https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file
[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404